### ISSUE TITLE
Lack of SynapseTransfer/NemisysTransfer plugin for Nukkit

### ISSUE THREAD

**Issue by kvetinac97** [iTXTech/Nemisys#1]
I have set up server in Nemysis, 3 clients on Nukkit using SynapseAPI, but Idk how transfer between clients without any transfer plugin.

**Comment by PeratX** [comment]
Nemisys is not functional yet. You need to write plugin to transfer. (the basic method are used in SynapseTransfer)

**Comment by FilleDev** [comment]
Can you make SynapseTransfer for Nukkit? ;)

**Comment by PeratX** [comment]
After Nemisys is functional, I will.
