### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by JackboyPlay** [iTXTech/Nemisys#106]
Hello folks, how can I send with a Nemisys Plugin a message to all players on the network?

**Comment by boybook** [comment]
You can write a plugin. Just register a TextPacket and then sendPacket to players.

**Comment by JackboyPlay** [comment]
@boybook cant find smething called "TextPacket" where is it?

**Comment by MisteFr** [comment]
can you explain me how to instal nemisys @boybook  ??

**Comment by vzlomka76** [comment]
@Misteboss https://github.com/iTXTech/Nemisys/wiki/How-to-set-up-Nemisys
