### ISSUE TITLE
Names with Space Nukkit

### ISSUE THREAD

**Issue by FilleDev** [iTXTech/Nemisys#11]
Hello!

Since Nukkit added support for space names I can't login on the Nukkit servers anymore.
@PeratX @boybook 
https://github.com/Nukkit/Nukkit/commit/10f891b3dff2a439b7674ca5595af3c7b45b59d4

**Comment by dktapps** [comment]
@File14 you don't need to tag them in every single post you make. They'll be notified anyway because they are watching the repository. All you're doing is spamming them.

**Comment by FilleDev** [comment]
Oh, I didn't know that.
