### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by remotevase** [iTXTech/Nemisys#114]
Does Nemisys work on Windows Machines? (Windows 7)

**Comment by Matthww** [comment]
Can you run java applications on windows?

**Comment by MattWAnderson** [comment]
smh...

**Comment by remotevase** [comment]
yes, but when I do, it creates a window with the  nemisys title, and it quickly stops responding. The screen also fills up with tons of strange information... It doesnt seem to work...

**Comment by Matthww** [comment]
What java version are you running?

**Comment by remotevase** [comment]
8.1 SDK

**Comment by Matthww** [comment]
> The screen also fills up with tons of strange information...

Can you share this information which is maybe important...

**Comment by remotevase** [comment]
I do not want to start up the program again and crash the machine again... But i will tell you what it is. The title of the program is "Nemisys ___ Load__ Memory___ players ___" something like that. It kept on repeating that over and over again, but updating it based on how much load it was, and how much memory it used...

**Comment by remotevase** [comment]
Bump, someone please?

**Comment by MattWAnderson** [comment]
Sounds like a bad compile, I could offer a compiled JAR or a remote session if interested to have a look.

**Comment by remotevase** [comment]
I used the latest one from here: https://gitlab.com/itxtech/nemisys/pipelines

**Comment by remotevase** [comment]
I extraced that jar, then used this start.cmd file: 
``` cmd
@echo off
java -jar nemisys.jar
```

**Comment by MattWAnderson** [comment]
email me at matt@mattwanderson.com

**Comment by remotevase** [comment]
Okay, thanks. I will also upload screenshots here.

**Comment by remotevase** [comment]
Starts normally:
![image](https://cloud.githubusercontent.com/assets/16277471/22355236/8eab359a-e3f7-11e6-8c19-fef39baa3994.png)

Then in a few seconds:
![image](https://cloud.githubusercontent.com/assets/16277471/22355235/8b4a9706-e3f7-11e6-8423-77e1e59a6fe1.png)

Java version: 
![image](https://cloud.githubusercontent.com/assets/16277471/22355239/94656d0c-e3f7-11e6-82ad-16914d39ab90.png)

**Comment by remotevase** [comment]
In the first screenshot, you can start to see the spammy grey text that you see in the second picture.

**Comment by JackNoordhuis** [comment]
Looks like you've got some sort of debug enabled @remotevase

**Comment by remotevase** [comment]
How would I fix this?

**Comment by SupremeMortal** [comment]
It's not debug enabled. The text should be in the title of the windows however it is being printed in the console and because the title is constantly updated with the information, it's being spammed in the console. The server should theoretically still work fine.

**Comment by MrPowerGamerBR** [comment]
@SupremeMortal Nukkit has the same issue (well, now it doesn't since I made a pull request to disable titleTick()), titleTick() randomly starts printing the title message in the console.

**Comment by SupremeMortal** [comment]
Should be disabled for now since a native library is needed to interact with the title in a command line window.

**Comment by MrPowerGamerBR** [comment]
@SupremeMortal in this case: Jansi.

I updated some libraries in Nukkit (JLine and improved Nukkit's command line by adding TAB complete) and then it started happening, then I sent a pull request to disable titleTick() while I can't find a solution. (And... well, who needs that title thingy?, it is more like an hack (because it uses ANSI characters to change the title) than a proper feature)
