### ISSUE TITLE
Humans have player skin

### ISSUE THREAD

**Issue by vzlomka76** [iTXTech/Nemisys#116]
**Nemisys:** https://github.com/iTXTech/Nemisys/commit/7a2476cd287ad0eddc0985c515f4ce5acb3b846b

All humans (statue) have player skin
![2017-01-18 16-39-13](https://cloud.githubusercontent.com/assets/16573760/22066203/ea5e0702-dd9c-11e6-9bb9-5c02726ffce2.png)
![2017-01-18 16-39-52](https://cloud.githubusercontent.com/assets/16573760/22066204/ea68d9de-dd9c-11e6-89ed-65c885593642.png)

**Comment by MisteFr** [comment]
can you explain me how to instal nemisys  @vzlomka76 ??

**Comment by vzlomka76** [comment]
@Misteboss https://github.com/iTXTech/Nemisys/wiki/How-to-set-up-Nemisys

**Comment by MisteFr** [comment]
I don't have synapse option in my genisys.yml, btw i start nemisys and all is working @vzlomka76

**Comment by MisteFr** [comment]
@vzlomka76 can you explain me how to make it working ^^

**Comment by SleepSpace9** [comment]
The reason why all human entities have your player skin is that Nemisys only uses the SkinData from LoginPacket and not PlayerListPacket (probably for more performance and less traffic). The only possibility to get it work is to modify Nemisys (and also SynapsePM) for using the FullPlayerListPacket with all SkinData and not only the FastPlayerListPacket without SkinData.

**Comment by vzlomka76** [comment]
@boybook can you fix it?

**Comment by Creeperface01** [comment]
Its player list issue

**Comment by JackboyPlay** [comment]
On my Nukkit servers it works without this issue
