### ISSUE TITLE
Skin Glitch

### ISSUE THREAD

**Issue by evolvedtm** [iTXTech/Nemisys#12]
Some players appear to have the same skin as the client.

OS: Ubuntu 64bit

**Comment by dktapps** [comment]
This is a client bug. It's been around for a veeeeeeery long time.

**Comment by FilleDev** [comment]
Same issuse! Please fix.

**Comment by FilleDev** [comment]
@dktapps No it's not a client bug. If I join the first client which is the main server there are no skin issuses but once I transfer to another server everyone has my skin!

**Comment by evolvedtm** [comment]
It has been fixed for a while, but now it has reappeared ever since I started using Nemisys

**Comment by FilleDev** [comment]
I think it's SynapseAPI.

**Comment by SleepSpace9** [comment]
Maybe the new PlayerListPacket (SPPv6) isn't fully implemented in the Synapse Clients (e.g. Genisys) and causes the skin glitch.
