### ISSUE TITLE
how to get all Synapse-Clients?

### ISSUE THREAD

**Issue by Bluplayz** [iTXTech/Nemisys#124]
i make a plugin for Tesseract and want to make a function which returns me all Servers as "Genisys-Server" instance so that i can get all informations and add something... hope any one can help me

**Comment by jarne** [comment]
You can't get the whole server instance of another synapse client, but you can get the server hash containing information like IP and port to transfer players with a function like this one: https://github.com/iTXTech/SynapseTransfer/blob/master/src/synapsetransfer/SynapseTransfer.php#L69
If you want to exchange information between servers, you should use MySQL or something like this.
