### ISSUE TITLE
Timeout on 1.1.0/1.1.1

### ISSUE THREAD

**Issue by vzlomka76** [iTXTech/Nemisys#130]
It does not happen to everyone, but my two friends have this, but when I looked at the console, I saw that it was not just from my friends. (View pictures)
I did not understand, on what it depends
Reinstalling the client does not help, restarting nemisys does not help
![hvwzjeih100](https://user-images.githubusercontent.com/16573760/27455389-c9be98a8-57a5-11e7-9d10-d8a6c9172e97.jpg)
![aqlbfpkzlcg](https://user-images.githubusercontent.com/16573760/27455390-c9bf523e-57a5-11e7-957c-1c7f56e157e8.jpg)
![gdqg72mb3_i](https://user-images.githubusercontent.com/16573760/27455408-d760409c-57a5-11e7-9e31-f5c0153444d4.jpg)

**Comment by vzlomka76** [comment]
@boybook This morning, one of my friends earned everything, he was able to enter.

**Comment by vzlomka76** [comment]
@boybook please help me, i don't know why it happens. As I understand it creates a session (Player class), but LoginPacket doesn't send.

**Comment by boybook** [comment]
Are you sure your game's version is 1.1?
It seens just happened on 1.0.x.

**Comment by vzlomka76** [comment]
@boybook yes, the version is the 1.1. But i can't reproduce this, but some players have this problem

**Comment by vzlomka76** [comment]
Sorry, real version is 1.0.8. It's not bug, close this
