### ISSUE TITLE
Nemisys keeps timeouting

### ISSUE THREAD

**Issue by kvetinac97** [iTXTech/Nemisys#131]
Nearly every hour it happens that Nemisys shows 100% use even on machine with good processor and not more than 50 players and freezes for something about 8 minutes, so players then keep timeouting. Why does this happen?

**Comment by vzlomka76** [comment]
Confirmed. Have 24 players on server and nemisys load 100%
![2017-07-02 13-05-16](https://user-images.githubusercontent.com/16573760/27768887-232b56aa-5f27-11e7-9dc1-dbaf292b40be.png)

**Comment by adamiss5138** [comment]
There is also high RAM usage after this lag (2-3.5GB)

**Comment by vzlomka76** [comment]
@adamiss5138 Why Nemisys eats so much RAM?

**Comment by adamiss5138** [comment]
@vzlomka76 Idk. It's normal RAM usage is 100-200MB. But then it lags and usage jumps to 2-3.5GB (
in my case)

**Comment by vzlomka76** [comment]
@adamiss5138 maybe I need to create a separate plugin that will run gc command automatically?

**Comment by Creeperface01** [comment]
I cannot reproduce this issue.

**Comment by kvetinac97** [comment]
Does new SynapseAPI commit change anything on this bug?

**Comment by kvetinac97** [comment]
Just turn on Nukkit side packet compressing to fix the bug.

**Comment by PeratX** [comment]
GG
