### ISSUE TITLE
Too many packets (DoS attack)

### ISSUE THREAD

**Issue by jarne** [iTXTech/Nemisys#18]
Hi,

Today, I've got an email from my provider's abuse. They noticed an outgoing 'DoS attack' from my server:

Aug 15 02:05:22 vh256-1041 kernel: [9989677.742671] MAXIMUM OF 10000 PAKETS/s: IN=venet0 OUT=eth0 SRC=178.254.40.**\* DST=73.241.91.**\* LEN=71 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=UDP SPT=19132 DPT=19132 LEN=51 MARK=0x9551 .

As you can see on the port, it looks like it's an issue with Nemisys. I'm running Nemisys on port 19132 and some Genisys with RackLib disabled on ports over 50000.

I'm sorry, but I have no logs of my server because I've disabled it. Have you any idea what the issue could be?

**Comment by dktapps** [comment]
Win10 Edition Beta has been discovered to have DDoS issues. This may be the cause.

**Comment by markeev** [comment]
iptables -I INPUT -p udp --dport 19132 -m state --state NEW -m recent --set --name DOS 
iptables -I INPUT -p udp --dport 19132 -m state --state NEW -m recent --update --seconds 60 --hitcount 20 --name DOS -j REJECT --reject-with icmp-port-unreachable
&u need some normal vds hosting

**Comment by jarne** [comment]
Thanks for your answers. I'm not sure if you understood me correctly, but your answers sounds like a client has attacked the server. But it was outgoing traffic, so Nemisys 'attacked' a client.

**Comment by MCPECentralv2** [comment]
savage
