### ISSUE TITLE
Invalid login

### ISSUE THREAD

**Issue by zFellowZ** [iTXTech/Nemisys#19]
I setup nemisys, copied the password and paste it into Genisys.yml then turned on syapse to on. But genisys is saying that the password is wrong.. but i actually paste it in.... This is a bug..

Can anyone help?

**Comment by xZeroMCPE** [comment]
Hmn, anybody else is having this issue? it seems to be happening with Nemisys only. I've tested it myself. But works fine with Nemisys!

**Comment by zFellowZ** [comment]
anyone can help ?

**Comment by zFellowZ** [comment]
I added my own password in the thingy and added it in genisys but no work!! please halp

**Comment by ghost** [comment]
@xZeroMCPE What port you use for server xyz in genisys.yml ?

**Comment by xZeroMCPE** [comment]
@NycuRO  Any port, it doesn't matter.
