### ISSUE TITLE
How to compile to jar ?

### ISSUE THREAD

**Issue by Pogogo007** [iTXTech/Nemisys#2]

**Comment by Creeperface01** [comment]
IntelliJ for example

**Comment by Creeperface01** [comment]
Or CircleCI

**Comment by Matthww** [comment]
If you are on linux

Install Maven

Debian/Ubuntu:

```
apt-get install maven
```

Centos:

```
yum install maven
```
1. download the zip file or git clone it
2. cd into the directory
3. type:

```
mvn clean
```
1. If it says "BUILD SUCCES" type this:

```
mvn package
```

If thats done you will see a new directory called target with the nemisys-1.0dev.jar

**Comment by dries-c** [comment]
i am using osx how i can compile?

**Comment by Matthww** [comment]
same thing I think

**Comment by dries-c** [comment]
can you post it for me?
the .jar file

**Comment by Matthww** [comment]
sure
https://transfer.sh/sIdKn/nemisys-1.0dev.jar

**Comment by dries-c** [comment]
it work

**Comment by kabluinc** [comment]
@flaxues the link u gave no longer works :( pls can u give me a download link to the nemesys.jar 

Many Many thanks!
