### ISSUE TITLE
Plugins not working on transfer.

### ISSUE THREAD

**Issue by StaticGamerYT** [iTXTech/Nemisys#20]
Hi,

when I transfer to a server players don't move and plugins don't work and I get kicked after several seconds. Both lobby and other server run on different IPs and on port 19132. This only happens when there are multiple players online, it doesn't occur when there are only 1 or 2 players.

Problem occurs on MCPE Windows 10 Edition and on Android 6.1 (Oneplus 2)

**Comment by xZeroMCPE** [comment]
I recommend using Synapse it has less bugs. Even though it's outdated it can always be updated with ease. Which would only take a few min(S).

**Comment by zFellowZ** [comment]
@StaticGamerYT I think it may be your hardware 😂

**Comment by StaticGamerYT** [comment]
@zFellowZ It can't be my hardware, it's running on a 32GB RAM dedi...

**Comment by zFellowZ** [comment]
@StaticGamerYT Ram doesn't mean a thing... It depends on the CP, cores... ect having that much of ram  doesn't mean a thing.. mate

**Comment by StaticGamerYT** [comment]
@zFellowZ it has a xeon with 8 cores... i don't buy cheap stuff

I don't get any errors, it just says that the player got disconnected because of timeout after a short time even though it doesn't disconnect me

**Comment by intagaming** [comment]
#13 related.

**Comment by XFuryMCPE** [comment]
@xZeroMCPE We are talking about official builds and things to be updated in the main branch, this is about Nemisys, NOT Synapse, even the developers recommend Nemisys over Synapse. Stop giving out bad information.

**Comment by xHFx** [comment]
The hardware of the server has nothing to do with these problems .... Now the device the player is on may have something to do with this but I have no idea

**Comment by ghost** [comment]
@xZeroMCPE You can help me please with Nemisys? I;m creating new issue ,you can help me please?
