### ISSUE TITLE
Server XYZ not work

### ISSUE THREAD

**Issue by ghost** [iTXTech/Nemisys#24]
I'm using port in server-proprietes : 19131

In genisys.yml ,i'm using : 19132

lobby : 19132 
nemisys : 19132.

Lobby conected to nemisys and XYZ server not. Why?

**Comment by ghost** [comment]
@boybook

**Comment by SleepSpace9** [comment]
@NycuRO Have a look at the Synapse Wiki: https://github.com/iTXTech/Synapse/wiki/How-to-setup
There you can see some basics, but beware that you should use now Nemisys and no more Synapse.

**Comment by PeratX** [comment]
It should be spp port not the mcpe port.
