### ISSUE TITLE
Raknet and Synlib crash on nemisys server start

### ISSUE THREAD

**Issue by alexbgameson** [iTXTech/Nemisys#29]
2016-8-27 10:21:20 [INFO] Loading server properties...
2016-8-27 10:21:21 [INFO] Selected English (eng) as the base language
2016-8-27 10:21:21 [INFO] Starting Minecraft: PE server version v0.15.0 alpha
2016-8-27 10:21:21 [INFO] Opening server on 0.0.0.0:19132
2016-8-27 10:21:21 [INFO] This server is running Nemisys version 1.0dev "Aegis" (API 1.0.0)
2016-8-27 10:21:21 [INFO] Nemisys is distributed under the LGPL License
2016-8-27 10:21:21 [INFO] Starting GS4 status listener
2016-8-27 10:21:21 [INFO] Setting query port to 19132
2016-8-27 10:21:21 [INFO] Query running on 0.0.0.0:19132
2016-8-27 10:21:21 [INFO] Done (2813s)! For help, type "help" or "?"
2016-8-27 10:21:21 [CRITICAL] ***\* FAILED TO BIND TO 0.0.0.0:19132!
2016-8-27 10:21:21 [CRITICAL] Perhaps a server is already running on that port?
2016-8-27 10:21:21 [EMERGENCY] RakNet crashed!
2016-8-27 10:21:21 [EMERGENCY] SynLib crashed!

**Comment by Matthww** [comment]
Perhaps a server is already running on that port?

READ THE ERROR!

**Comment by dktapps** [comment]
Closing due to [redacted probably offensive statement]. (^_^)
