### ISSUE TITLE
Out of bounds crash

### ISSUE THREAD

**Issue by Guillaume351** [iTXTech/Nemisys#32]
Hello,
after running the server for a few hours, I get this error :

> 15:41:26 [INFO] josehackernoob has been transferred to 127.0.0.1:38647
> 15:41:28 [INFO] Jerick24[/130.105.214.33:19132] logged out due to timeout
> 15:41:36 [INFO] Sasha has been transferred to 127.0.0.1:40928
> 15:41:37 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 1024
>         at org.itxtech.nemisys.utils.Binary.splitBytes(Binary.java:287)
>         at org.itxtech.nemisys.raknet.server.Session.addEncapsulatedToQueue(Session.java:266)
>         at org.itxtech.nemisys.raknet.server.SessionManager.receiveStream(SessionManager.java:320)
>         at org.itxtech.nemisys.raknet.server.SessionManager.tickProcessor(SessionManager.java:90)
>         at org.itxtech.nemisys.raknet.server.SessionManager.run(SessionManager.java:69)
>         at org.itxtech.nemisys.raknet.server.SessionManager.<init>(SessionManager.java:57)
>         at org.itxtech.nemisys.raknet.server.RakNetServer.run(RakNetServer.java:101)

15:46:23 [INFO] ENDER_SPIDER[/85.101.213.4:10236] logged out due to timeout
15:46:28 [INFO] Prince_Troy_III[/50.156.91.147:19132] logged out due to timeout
15:46:30 [INFO] jppogi[/121.54.32.170:7992] logged out due to timeout
15:46:31 [INFO] Jack[/83.69.0.11:42282] logged out due to timeout

Thanks

**Comment by MichaelM04** [comment]
#33 Same issues, perhaps close one?

**Comment by Guillaume351** [comment]
@MichaelM04 @PeratX I created two issues because it's not the same error :/
