### ISSUE TITLE
Nemisys compiled

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Nemisys#35]
@flaxues or anyone with a compiled nemisys.jar file please could u give me a download link to one. Iv literally spent hours trying to compile it with circlecI but get account errors, tried maven but no luck

Thanks allot

Ps. Sorry that this issue is completely off-topic but any help would be much appreciated!

**Comment by corndan** [comment]
https://gitlab.com/itxtech/nemisys/builds/2807074/artifacts/download

/target/nemisys-1.0dev.jar

**Comment by kabluinc** [comment]
Thanks so much!
