### ISSUE TITLE
Servers connected to Nemisys timing out and players recieve server closed

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Nemisys#38]
Every now and then all synapse servers time out from nemisys and players logout due to server closed. this happens more when 5-10 players are online

**Comment by AppleMinerHD** [comment]
Same Problem

**Comment by XFuryMCPE** [comment]
Well I sort of reproduced this. If one player is AFK for around 2-3 minutes, only THEY get the timeout and disconnect. No one else disconnects and the client stays connected.

**Comment by Creeperface01** [comment]
i can confirm this, but it happens very often for me. ussually on join...

**Comment by Creeperface01** [comment]
but maybe its a synapse issue

**Comment by Creeperface01** [comment]
probably synapse stucks somewhere

**Comment by Creeperface01** [comment]
nemisys doesn't receive HeartBeatPacket

**Comment by Creeperface01** [comment]
OMG @boybook can you comment this issue?? or do you think its not important??

**Comment by MattWAnderson** [comment]
Try this:
https://github.com/iTXTech/Nemisys/issues/51

**Comment by boybook** [comment]
See https://github.com/iTXTech/SynapseAPI/issues/19

**Comment by boybook** [comment]
See https://github.com/iTXTech/Nemisys/issues/49

**Comment by boybook** [comment]
Fixed in https://github.com/iTXTech/Nemisys/commit/1cf4a94524d74c272c485c9041f29cce9bd3d106
