### ISSUE TITLE
[REQUEST] Refresh clients data more often

### ISSUE THREAD

**Issue by Guillaume351** [iTXTech/Nemisys#40]
Hello,
I use 3 clients right now :
Hub - game1 - game2.

On hub, I get playercount of game1 and game2 using the client data of synapse.
However, the playercount is only refreshed if a new Synapse client connects to Nemisys.
So the data is not refreshed unless game1 or game2 reboots.

Would it be possible to refresh every X seconds or when a new player connects/disconnects ?

Thanks

**Comment by SleepSpace9** [comment]
It would also be great if the names of all online players were put into the synapse client data array 
(of course only if it doesn't decrease performance).

**Comment by Guillaume351** [comment]
Maybe an API to get manually informations from a certain client ... As this, it doesn't refresh for people that don't use this data.

**Comment by XFuryMCPE** [comment]
How about you connect a useless test client to the server, which reboots everytime you want to refresh the counts?

**Comment by XFuryMCPE** [comment]
Just tested that ^^ works

**Comment by SleepSpace9** [comment]
@XFuryMCPE Sounds more like a workaround, I would prefer a clean solution.
But thanks for tip! :+1:

**Comment by PeratX** [comment]
The client info is the response to the HeartbeatPacket, so you can change the heartbeat time in client.

**Comment by Guillaume351** [comment]
@PeratX But the heartbeat refresh data on the Nemisys server, it doesn't send the info of game1 and 2 to hub ? (In my example)

**Comment by SleepSpace9** [comment]
The line `this.server.updateClientData();` is missing in the heartbeat section in **Client.java**.
It's only done at "case SynapseInfo.CONNECT_PACKET: ..." and that's the reason why the client data only refreshs at connect. After I put it also at "case SynapseInfo.HEARTBEAT_PACKET: ..." it works!

**Comment by Guillaume351** [comment]
@PeratX Please reopen :/ @SleepSpace9 fix is working for me, could you apply it ? I don't really know how  to create a clean pull request :/

**Comment by SleepSpace9** [comment]
@Guillaume351 If you use my fork (update to 0.15.9 still missing there) you even get a comma separated list of all Synapse players in ClientData.

You can fetch it like this:

```
foreach($this->getServer()->getSynapse()->getClientData() as $cdata){
    echo "Players on server ".$cdata["description"].":\n".$cdata["playerNames"]."\n";
}
```

I use it for my own /list command. Possibly some more people like it.  😉
