### ISSUE TITLE
[REQUEST] Update Nemisys to More Stability

### ISSUE THREAD

**Issue by marcosvkp** [iTXTech/Nemisys#41]
![image](https://cloud.githubusercontent.com/assets/15146680/18234480/74546184-72dd-11e6-8bca-8502fda3d3fb.png)

Server to Host: 4gb Memory Dedicated to Nemisys
Server have 6 Cores

Player join in server, crash player "server closed"

**Comment by PeratX** [comment]
That's your server's config issue.
