### ISSUE TITLE
wtf?

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Nemisys#43]
15:24:05 [INFO] ---- Server status ----
15:24:05 [INFO] Uptime: 0 days 3 hours 39 minutes 51 seconds
15:24:05 [INFO] Current TPS: 100.0
15:24:05 [INFO] Load: 0.15%
15:24:05 [INFO] Network upload: 28.45 kB/s
15:24:05 [INFO] Network download: 36.68 kB/s
15:24:05 [INFO] Thread count: 14
15:24:05 [INFO] Used memory: 1301.79 MB. (18.22%)
15:24:05 [INFO] Total memory: 2809.0 MB.
15:24:05 [INFO] Maximum VM memory: 7145.0 MB.
15:24:05 [INFO] Available processors: 8
15:24:05 [INFO] Players: 4 online, 1000 max.

USED MEMORY 1301MB??? wtf

15:24:14 [INFO] ---- Garbage collection result ----
15:24:14 [INFO] Memory freed: 1295.86 MB

thats crazy...

**Comment by tarik02** [comment]
Try to schedule System.gc() every five minues.

**Comment by xZeroMCPE** [comment]
I think it's that Server.log thing -.- keeps writing to the file..... That's mainly why i think it should be removed.
