### ISSUE TITLE
wtf?x2

### ISSUE THREAD

**Issue by hhm233** [iTXTech/Nemisys#47]
My server uses SynapseTransfer with Nemisys, there are 3 servers, into the oral (Hall), survival server and entertainment server. There is no mistake in entering the oral administration. However, when entering the non main server, the MinecraftPE will crash when the return key. And after entering the main city is not in the player's last landing position.（Baidu Translate don't mind 2333 ）

**Comment by hhm233** [comment]
Is MinecraftPE itself a problem or a problem here?

**Comment by legoboy0215** [comment]
Problem here.

**Comment by hhm233** [comment]
When can we solve this problem?

**Comment by boybook** [comment]
可否说中文？？
