### ISSUE TITLE
IOS clients crashing

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Nemisys#48]
IOS users are constantly crashing when joining the main server. whenever they join they keep timing out. when synapse/nemisys is disabled no one crashes

**Comment by File14** [comment]
I almost got the same issuse, for me. IOS clients crash when people join the server. (Sometimes)

**Comment by Creeperface01** [comment]
windows 10 too. or stuck in building terrain screen

**Comment by xZeroMCPE** [comment]
@File14 @Creeperface01  Hmn i've tested it. And here are the results

Window 10: ( Does not crash, nor stuck on building terrain screen )
IOS:  ( Crashes, sometimes or when building the tarrain)

It crashes most on ios. Try to disable "raknet". I think it should fix it or has something to do with it

**Comment by File14** [comment]
@xZeroMCPE Yes, as I said. I have this issuse on IOS. But for me it crashes often if the you login with a IOS device and then if another guy joins the server it crashes the IOS guy.

**Comment by File14** [comment]
Also I have disabled raknet. ^^

**Comment by xZeroMCPE** [comment]
@File14 Did you test it while raknet was enabled?

**Comment by File14** [comment]
Nope, but why would it just crash for IOS then not Windows 10 etc...?

**Comment by MattWAnderson** [comment]
We had some issues when raklib was disabled. Currently is not and seems to work for everyone. Can test at hub.pocketminers.com  We run a single nemisys with multidle hubs.

**Comment by File14** [comment]
My crash issuse only seems to appear once the player is transferred into another server. (not the main server).

**Comment by xZeroMCPE** [comment]
@File14 uhm, maybe it's an issue that targets ios users? eh

**Comment by FilleDev** [comment]
hmm idk
