### ISSUE TITLE
Nemisys server times out and acts as if its offiline

### ISSUE THREAD

**Issue by alexbgameson** [iTXTech/Nemisys#49]
Nemisys server times out and acts as if its offiline.

**Comment by Creeperface01** [comment]
OMG @boybook can you comment this issue?? or do you think its not important??

**Comment by SleepSpace9** [comment]
Maybe relatet to this issue: https://github.com/iTXTech/Nemisys/issues/54 ?

**Comment by Creeperface01** [comment]
Of course

**Comment by Creeperface01** [comment]
But i want to know if devs noticed this bug or just ignoring it

**Comment by boybook** [comment]
See https://github.com/iTXTech/SynapseAPI/issues/19
