### ISSUE TITLE
Nemisys crash by java.net.SocketException: Invalid argument

### ISSUE THREAD

**Issue by SleepSpace9** [iTXTech/Nemisys#51]
**Issue description**
About one or two times a day a connecting MCPE client (or something else) is causing a Nemisys server crash because of invalid arguments at UDP socket connection. When the exception occures the traffic stops and all other clients are timing out. Then I have to kill the process and restart Nemisys.

Maybe the causing client is using a wrong port number for it's own address (e.g. "0"), so that InetSocketAddress becomes invalid.
In my Nemisys server.properties I set `server-ip=0.0.0.0`and `server-port=19132` so this should be valid. I also disabled RakLib on all Genisys servers, so the only UDP connection happens between Nemisys server and MCPE(?) client.

Is there a way to prevent this annoying exception (try/catch or something else) ?

**OS and versions**
- Nemisys: commit 8402333
- Genisys: commit https://github.com/iTXTech/Genisys/commit/9c13370ec33dad0e4f096447dbc5fd597f06d75a
  - This server is running Genisys (codename "Kyrios")
  - API: 2.0.0 (iTX API version 1.9.2)
  - Target client: Minecraft PE v0.15.4 alpha (protocol version 82)
- PHP: 7.0.9
- Server OS: Ubuntu server 14.04

**Output from crash**

```
2016-9-19 03:48:26 [INFO] NOTCH[/189.224.80.xxx:19132] logged in with client id -7269041299459283093
2016-9-19 03:48:26 [INFO] NOTCH has been transferred to Lobby (127.0.0.1:43142)
2016-9-19 03:48:27 [NOTICE] Blocked 190.128.114.xxx for 300 seconds
2016-9-19 03:48:31 [INFO] Steve[/24.190.240.xxx:19132] logged out due to client disconnect
2016-9-19 03:48:37 [INFO] NOTCH[/189.224.80.xxx:19132] logged out due to client disconnect
2016-9-19 03:48:37 [ALERT] java.net.SocketException: Invalid argument
        at sun.nio.ch.DatagramChannelImpl.send0(Native Method)
        at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:521)
        at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:498)
        at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462)
        at org.itxtech.nemisys.raknet.server.UDPServerSocket.writePacket(UDPServerSocket.java:83)
        at org.itxtech.nemisys.raknet.server.UDPServerSocket.writePacket(UDPServerSocket.java:78)
        at org.itxtech.nemisys.raknet.server.SessionManager.sendPacket(SessionManager.java:197)
        at org.itxtech.nemisys.raknet.server.Session.sendPacket(Session.java:189)
        at org.itxtech.nemisys.raknet.server.Session.addToQueue(Session.java:225)
        at org.itxtech.nemisys.raknet.server.Session.addEncapsulatedToQueue(Session.java:295)
        at org.itxtech.nemisys.raknet.server.Session.close(Session.java:532)
        at org.itxtech.nemisys.raknet.server.SessionManager.removeSession(SessionManager.java:431)
        at org.itxtech.nemisys.raknet.server.Session.disconnect(Session.java:185)
        at org.itxtech.nemisys.raknet.server.Session.update(Session.java:109)
        at org.itxtech.nemisys.raknet.server.SessionManager.tick(SessionManager.java:107)
        at org.itxtech.nemisys.raknet.server.SessionManager.tickProcessor(SessionManager.java:100)
        at org.itxtech.nemisys.raknet.server.SessionManager.run(SessionManager.java:69)
        at org.itxtech.nemisys.raknet.server.SessionManager.<init>(SessionManager.java:57)
        at org.itxtech.nemisys.raknet.server.RakNetServer.run(RakNetServer.java:101)

2016-9-19 03:52:47 [INFO] kevguygames[/76.219.169.xxx:19132] logged out due to timeout
2016-9-19 03:53:28 [INFO] vale_yiyi[/189.215.225.xxx:62391] logged out due to timeout
2016-9-19 03:53:30 [INFO] renanbr1234567[/187.11.58.xxx:19132] logged out due to timeout
2016-9-19 03:53:34 [INFO] DarknessAngel[/70.126.211.xxx:19132] logged out due to timeout
```

**Comment by boybook** [comment]
???It looks like the crash of Raknet from Nukkit.

**Comment by boybook** [comment]
I use Nukkit with SynapseAPI, never crash like this.

**Comment by SleepSpace9** [comment]
The Genisys servers also need a restart after this crash. They don't notice a connection loss und so they don't automatically retry a connect.

**Comment by SleepSpace9** [comment]
I'm already using the java start parameter `-Djava.net.preferIPv4Stack=true` to prefer IPv4, because I read of corresponding problems with IPv6. But sadly didn't help.

**Comment by SleepSpace9** [comment]
I changed the code to check if the destination port is in the range of 1 to 65535 and log if not. We'll see what happens...

**Comment by Guillaume351** [comment]
@SleepSpace9 Same issue here I think. Nemisys - Genisys

> 2016-9-24 00:25:01 [INFO] MentMin has been transferred to hub1
> 2016-9-24 00:25:02 [ALERT] java.net.SocketException: Invalid argument
>     at sun.nio.ch.DatagramChannelImpl.send0(Native Method)
>     at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:521)
>     at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:498)
>     at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462)
>     at org.itxtech.nemisys.raknet.server.UDPServerSocket.writePacket(UDPServerSocket.java:83)
>     at org.itxtech.nemisys.raknet.server.UDPServerSocket.writePacket(UDPServerSocket.java:78)
>     at org.itxtech.nemisys.raknet.server.SessionManager.sendPacket(SessionManager.java:197)
>     at org.itxtech.nemisys.raknet.server.Session.sendPacket(Session.java:189)
>     at org.itxtech.nemisys.raknet.server.Session.addToQueue(Session.java:225)
>     at org.itxtech.nemisys.raknet.server.Session.addEncapsulatedToQueue(Session.java:295)
>     at org.itxtech.nemisys.raknet.server.Session.close(Session.java:532)
>     at org.itxtech.nemisys.raknet.server.SessionManager.removeSession(SessionManager.java:431)
>     at org.itxtech.nemisys.raknet.server.Session.disconnect(Session.java:185)
>     at org.itxtech.nemisys.raknet.server.Session.update(Session.java:109)
>     at org.itxtech.nemisys.raknet.server.SessionManager.tick(SessionManager.java:107)
>     at org.itxtech.nemisys.raknet.server.SessionManager.tickProcessor(SessionManager.java:100)
>     at org.itxtech.nemisys.raknet.server.SessionManager.run(SessionManager.java:69)
>     at org.itxtech.nemisys.raknet.server.SessionManager.<init>(SessionManager.java:57)
>     at org.itxtech.nemisys.raknet.server.RakNetServer.run(RakNetServer.java:101)

**Comment by SleepSpace9** [comment]
YAY! My guess was right - somebody uses the invalid destination port "**0**", which causes the exception.
In this case my special alert was triggert and I always return 0 in the writePacket function of the UDPServerSocket class, so my Nemisys doesn't crash anymore. Now I'm again at 100% uptime. :tada:

```
2016-9-25 06:30:55 [ALERT] @SleepSpace9: Invalid destination port for client address => 0 (dest=/191.180.31.xxx:0)
2016-9-25 06:30:56 [ALERT] @SleepSpace9: Invalid destination port for client address => 0 (dest=/191.180.31.xxx:0)
2016-9-25 06:30:56 [ALERT] @SleepSpace9: Invalid destination port for client address => 0 (dest=/191.180.31.xxx:0)
2016-9-25 06:30:57 [ALERT] @SleepSpace9: Invalid destination port for client address => 0 (dest=/191.180.31.xxx:0)
```

I also noticed another bug, which causes the query server of Nemisys to block incoming queries. The server then seems to be offline for server lists, but not real.
This situation is also  simple to explain. There's a player (or bot for other purposes) with the super cool name "null". Since I kick players with the name "null" when parsing the LOGIN_PACKET this error has also gone away.

**Comment by MattWAnderson** [comment]
Do we have a commit or instructions on testing this? - Would like to give this a try.

**Comment by Guillaume351** [comment]
@SleepSpace9 I will give this a try, thanks ! :)

**Comment by SleepSpace9** [comment]
These commits should fix this issue (_java.net.SocketException: Invalid argument_)
https://github.com/SleepSpace9/Nemisys/commit/701e7d1683288f1b689bffb20b92ab624f63cd9d + https://github.com/SleepSpace9/Nemisys/commit/46674b3ed4ca862e6fcdb3b9d936dd8098031cc3

I'll create another one for the query error.

**Comment by SleepSpace9** [comment]
Here's the next workaround for the second issue (https://github.com/iTXTech/Nemisys/issues/54 and probably https://github.com/iTXTech/Nemisys/issues/49 and maybe even https://github.com/iTXTech/Nemisys/issues/38): 

https://github.com/SleepSpace9/Nemisys/commit/b6b7de20c12bf1028a898217301a0e2f3bdbc7db

**Comment by MattWAnderson** [comment]
Working well here.

**Comment by jarne** [comment]
@SleepSpace9 Why don't create a PR, it's working great for me.

**Comment by MattWAnderson** [comment]
Same here.

**Comment by SleepSpace9** [comment]
Okay, I just wanted to wait for a positive feedback. Thank you, I'll do it! :+1:

**Comment by boybook** [comment]
See https://github.com/iTXTech/Nemisys/commit/1cf4a94524d74c272c485c9041f29cce9bd3d106

**Comment by SleepSpace9** [comment]
Okay I guess I can close this issue because it works more reliable now. 
Thank you for keeping Nemisys alive! 👍
