### ISSUE TITLE
Have players be teleported to default server after crash/shutdown

### ISSUE THREAD

**Issue by DaMatrix** [iTXTech/Nemisys#55]
Rather than having all my players have to relog every 3 hours because of AutoRestart, would it be possible to instead have them be teleported back to the (default) lobby server?

**Comment by xZeroMCPE** [comment]
After the last 1 seconds of restart move the player to another server. Then after from that other server move them back.

Just edit the restart plugin your using and implement that feature i just stated above.
Easy isn't it?

Nemisys shouldn't have alot of features. It job is to maintain / fix bugs etc. Other things should get handle by plugins similar to BungeeCord only basic things are on it and other things you'd need to develop plugins for it :)

**Comment by DaMatrix** [comment]
I guess, I just feel it should be built into tje proxy. It is on BungeeCord

Sent from my Samsung device

-------- Original message --------

**Comment by MattWAnderson** [comment]
+1 for org request. If packets fail to redirect if they fell back to the hub servers that would be amazing.

**Comment by boybook** [comment]
Write a plugin to achieve this function is the best choice.
