### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by MrReskill** [iTXTech/Nemisys#61]
Hey,
All plugins will load but nothing works (PlayerJoin onCommand onMove [..]) nothing even onCommand etc of this or vien? (No error in the console)

**Comment by MrReskill** [comment]
Please ;(

**Comment by xZeroMCPE** [comment]
I have not tested any. But again, mind sharing what you was trying to do? like the code and i'll try myself!

**Comment by undrfined** [comment]
@MrReskill are you registered events and implement Listener in your class?

**Comment by SupremeMortal** [comment]
I just created a simple plugin. Looks like the Synapse clients have higher priority than the Synapse server.
@xZeroMCPE Here is some code I created: https://github.com/SupremeMortal/SynapseTransfer

**Comment by SupremeMortal** [comment]
You can tell this is the case as the command works in the console of the Nemisys server without any errors.
Can someone mark this as a bug?

**Comment by SupremeMortal** [comment]
Anyone going to fix this anytime soon? It's a major feature that is broken. @boybook

**Comment by ghost** [comment]
@PeratX @boybook You can fix,please?

**Comment by PeratX** [comment]
You must understand, this is a proxy server not a GAME SERVER. Any Player Tiggered Event are available.
