### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by transdeveloper** [iTXTech/Nemisys#71]
how do i compile it ??? with eclipse

**Comment by DaMatrix** [comment]
You don't use eclipse, you use maven. `cd` into the dir where you cloned Nemisys into until you find a dir with a file inside named `pom.xml`. Then do `mvn clean install` and the jar will be put into `target`.

-------- Original message --------

**Comment by transdeveloper** [comment]
im doing it on osx it wont work

**Comment by DaMatrix** [comment]
Then I guess it's time for you to go get a operating system that is worth something huh?

-------- Original message --------
