### ISSUE TITLE
Doesnt connect to servers running 16.0

### ISSUE THREAD

**Issue by alexbgameson** [iTXTech/Nemisys#79]
The server cannot connect to the synapse client. It says that the client is not verified in the nemisys console.

**Comment by FilleDev** [comment]
I can't connect to 0.16 because it's not updated yet.

**Comment by alexbgameson** [comment]
Genisys is updated!

**Comment by DaMatrix** [comment]
No it's not!

**Comment by alexbgameson** [comment]
yes, the unsupported phar is out!

**Comment by alexbgameson** [comment]
You can download it here! [https://gitlab.com/itxtech/genisys/pipelines/4799730](url)

**Comment by alexbgameson** [comment]
You can download it here https://gitlab.com/itxtech/genisys/pipelines/4799730

**Comment by DaMatrix** [comment]
it's __UNSUPPORTED__. that means that it's __UNSUPPORTED__.

**Comment by DaMatrix** [comment]
![screenshot from 2016-10-29 22-51-23](https://cloud.githubusercontent.com/assets/11216106/19832662/4b048ad4-9e2a-11e6-9a73-88714a2f4bb7.png)

**Comment by boybook** [comment]
Now I'm working on SynapseAPI but there are lot's if bugs happened. So please wait for it.
