### ISSUE TITLE
Plugins wont load

### ISSUE THREAD

**Issue by ItzWalla** [iTXTech/Nemisys#8]
07:17:27 [INFO] Loading server properties...
07:17:27 [INFO] Selected English (eng) as the base language
07:17:27 [INFO] Starting Minecraft: PE server version v0.15.0 alpha
07:17:27 [INFO] Opening server on 0.0.0.0:19132
07:17:27 [INFO] This server is running Nemisys version 1.0dev "Aegis" (API 1.0.0)
07:17:27 [INFO] Nemisys is distributed under the LGPL License
07:17:27 [INFO] Synapse Server is running on 0.0.0.0:10305
07:17:27 [INFO] Loading InfiniteTeleport v1.0.0

> Exception in thread "main" java.lang.NoClassDefFoundError: cn/nukkit/plugin/PluginBase
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
>         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>         at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
>         at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
>         at org.itxtech.nemisys.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44)
>         at org.itxtech.nemisys.plugin.JavaPluginLoader.getClassByName(JavaPluginLoader.java:146)
>         at org.itxtech.nemisys.plugin.PluginClassLoader.findClass(PluginClassLoader.java:40)
>         at org.itxtech.nemisys.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         at org.itxtech.nemisys.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:48)
>         at org.itxtech.nemisys.plugin.PluginManager.loadPlugin(PluginManager.java:83)
>         at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:264)
>         at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:119)
>         at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:111)
>         at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:107)
>         at org.itxtech.nemisys.Server.<init>(Server.java:166)
>         at org.itxtech.nemisys.Nemisys.main(Nemisys.java:48)
> Caused by: java.lang.ClassNotFoundException: cn.nukkit.plugin.PluginBase
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>         at org.itxtech.nemisys.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44)
>         at org.itxtech.nemisys.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         ... 23 more

**Comment by marcosvkp** [comment]
Is Nemisys, not Nukkit
