### ISSUE TITLE
0.16 MOTD?

### ISSUE THREAD

**Issue by FilleDev** [iTXTech/Nemisys#82]
Hello, I'm running the lastest version of Nemisys and I can't see the MOTD of the server on a 0.16 client. But if I click the server it will join but why cannot I see the MOTD? Is it a bug or have you guys forgot to update it?

**Comment by MrPowerGamerBR** [comment]
Isn't this a MCPE bug? I thought every 0.16 server won't show a MOTD

**Comment by FilleDev** [comment]
I don't know

**Comment by alexbgameson** [comment]
File14 how did you get nemisys to work with your 16.0 server?

**Comment by alexbgameson** [comment]
@File14 how did you get nemisys to work with 16.0?

**Comment by SleepSpace9** [comment]
He's probably using Nukkit, not Genisys.
