### ISSUE TITLE
I see that you added 16.0 support but...

### ISSUE THREAD

**Issue by alexbgameson** [iTXTech/Nemisys#83]
I see that you added 16.0 support. Can you add a compiled jar to the repository?

**Comment by DaMatrix** [comment]
there's this new thing called _maven_. use it.

**Comment by FilleDev** [comment]
Use maven.

**Comment by alexbgameson** [comment]
@File14 I dont know how to set up maven. Could you send the compiled jar you have? My email is alexbgames1@gmail.com

**Comment by DaMatrix** [comment]
you clone the repo, `cd` into the folder, and `mvn package`.
you could just run this "bash script": `git clone https://github.com/iTXTech/Nemisys.git; cd Nemisys; mvn clean install; cd target`. That won't work if you're on windows, and if you're on windows then take your computer and KILL IT WITH FIRE

**Comment by alexbgameson** [comment]
Yes, I have windows. I will through the window now

**Comment by alexbgameson** [comment]
I have winodws. I will through my computer off the roof now.

**Comment by alexbgameson** [comment]
But seriously, @DaMatrix can you send me the compiled jar?

**Comment by jarne** [comment]
https://gitlab.com/itxtech/nemisys/pipelines

**Comment by boybook** [comment]
Now I'm working on SynapseAPI but there are lot's if bugs happened. So please wait for it.
