### ISSUE TITLE
Transfer

### ISSUE THREAD

**Issue by orangetictac** [iTXTech/Nemisys#86]
Hello, i just installed nemisys, seted up it with instruction, downloaded and installed plugin SynapseTransfer. I see in Console "Login success...". I joined to my server, wrote /scid xyz XYZ after this i wrote /transfer xyz and nothing happened, in console i see that to_OXa trasfered to .... but in game i dont transfer! Please help me

**Comment by FilleDev** [comment]
I can't transfer to other servers via SynapseAPI because it crashes the client.

**Comment by SupremeMortal** [comment]
I fixed it by disabling raknet in the SynapseAPI config

**Comment by boybook** [comment]
It has been fixed by lastest SynapseAPI.
