### ISSUE TITLE
After transfer STUCK?

### ISSUE THREAD

**Issue by FilleDev** [iTXTech/Nemisys#88]
Hello!

Once I have transfered to a server I get stuck and cannot move, however I can type commands and chat.
I'm transfering via SynapseAPI.

Please fix the isssuse so you can transfer between servers again. @boybook

**Comment by xZeroMCPE** [comment]
Before you make issues, read other(S). 

This has been explained multiple times...,,,

**Comment by File14** [comment]
@xZeroMCPE Like where?
