### ISSUE TITLE
Incompatible SPP Version

### ISSUE THREAD

**Issue by FunnyBuddys** [iTXTech/Nemisys#89]
Hello,

I use Nemisys and i need the Compiled JAR. I doesn´t have Linux to Compile it self with Maven.

Thanks for Help.

**Comment by DaMatrix** [comment]
then compile it on your windows.

**Comment by FunnyBuddys** [comment]
Done. But `Client 127.0.0.1:32925 has disconnected due to Incompatible SPP version! Require SPP version: 7`

**Comment by DaMatrix** [comment]
Genisys doesn't work with the newest version of Nemisys.

**Comment by alexbgameson** [comment]
Do you know when it will update?

**Comment by SupremeMortal** [comment]
SynapseAPI for Nukkit has been updated it is imperative that you use 0.16.0

**Comment by MattWAnderson** [comment]
Use NetBeans (on Windows) to compile Nemisys.

**Comment by DaMatrix** [comment]
@alexbgameson https://github.com/iTXTech/Genisys/pull/2138

**Comment by FunnyBuddys** [comment]
Work SynapseAPI for Genisys?

**Comment by DaMatrix** [comment]
.... it's a nukkit plugin
