### ISSUE TITLE
building screen issue?

### ISSUE THREAD

**Issue by Creeperface01** [iTXTech/Nemisys#95]
sometimes something wrong happens in nemisys and players can not join anymore, always get stuck in building terrain, so i must restart the server

(doFirstSpawn method isn't called)

**Comment by Creeperface01** [comment]
@boybook idk how you can run nemisys without these issues :D maybe you are incredibly lucky or you have your own modified version :D

**Comment by Creeperface01** [comment]
hmmm its SynapseAPI issue probably. Anyway, nemisys and synapse are really buggy :/ and they are not usable for now :/ i had to make lots of workarounds to get it working well

**Comment by boybook** [comment]
Yes, it also happened in my server sometimes. I am also very worried, Because I can not accurately reproduce the problem, so I can not find specific reasons. I tried a lot of ways, but only to ease.

**Comment by boybook** [comment]
I need your help to fix it. I suspect that this is caused by the network of binary transmission, including data packet cutting and so on.

**Comment by boybook** [comment]
I suspect that this is caused by the network of binary transmission, including data packet cutting and so on. When I update Nukkit to 0.16, I found it will happen of the error of the EntityMetadata encoding.

**Comment by boybook** [comment]
This may be too much data transmission in the 1tick, which led to a part of being discarded. So if it cut the data sending of entity(Send too many chunk datas), It will happen.

**Comment by Creeperface01** [comment]
I changed world format from region to anvil and it doesnt happen

**Comment by Creeperface01** [comment]
Nemisys also has old Zlib (my pull request)

**Comment by boybook** [comment]
OMG!

**Comment by boybook** [comment]
Fixed in https://github.com/iTXTech/Nemisys/commit/1cf4a94524d74c272c485c9041f29cce9bd3d106
