### ISSUE TITLE
Maven Java Compile (ERROR) [Debian]

### ISSUE THREAD

**Issue by transdeveloper** [iTXTech/Nemisys#98]
i get a error of build failure

**Comment by DaMatrix** [comment]
... can we get more information?

**Comment by SupremeMortal** [comment]
Probably just an issue on your side since I have Jenkins running on Debian 8 fine
https://ci.potestas.xyz

**Comment by Goodstuff4UonYT** [comment]
I can't compile it, too.
If you compile it with maven you get a lot of errors.
If you put Nemisys into a Project of Ecclipse everything is red.

**Comment by xZeroMCPE** [comment]
Everything works fine for me, Make sure you have java 8 or ( > )

**Comment by Goodstuff4UonYT** [comment]
java version "1.8.0_101"

**Comment by SupremeMortal** [comment]
I gave you a link to download it. Don't see why you are still trying to compile it.
https://ci.potestas.xyz/job/Nemisys/

**Comment by Goodstuff4UonYT** [comment]
Because I changed some things...

**Comment by SupremeMortal** [comment]
@Goodstuff4UonYT If you changed things, then it's because you have compilation errors. You probably didn't use an IDE by looking at your fork.

**Comment by Goodstuff4UonYT** [comment]
I have also errors with the unedited version...
IDE: "If you put Nemisys into a Project of Ecclipse everything is red."

**Comment by SupremeMortal** [comment]
Because you need to use maven to create the eclipse project files. I think you need to watch some tutorials instead of making invalid issues

**Comment by Goodstuff4UonYT** [comment]
And if i put the UNEDITED project to the server and want to built it with maven. I can't compile it...
In the past it works... 
And I don't open this issue.

**Comment by SupremeMortal** [comment]
http://maven.apache.org/plugins/maven-eclipse-plugin/

**Comment by Goodstuff4UonYT** [comment]
"And if i put the UNEDITED project to the server and want to built it with maven. I can't compile it..." This have nothing to do with Eclipse.

**Comment by SupremeMortal** [comment]
Well, that's something wrong with your environment.
https://ci.potestas.xyz/job/Nemisys/19/console

**Comment by Goodstuff4UonYT** [comment]
sure...
