### ISSUE TITLE
Hostname Server

### ISSUE THREAD

**Issue by uselesswaifu** [iTXTech/Nemisys#99]
A feature to choose which server to send players based on the Hostname, Similiar to BungeeCord.. For Example if I used the Domain factions.example.com it would send Players to my Factions server

**Comment by SupremeMortal** [comment]
Yeah. Using the request hostname header to determine which server they join.

**Comment by uselesswaifu** [comment]
@SupremeMortal I fixed my english problems 👍 Do you know how to Achieve this?

**Comment by boybook** [comment]
How to Nemisys know the hostname of your servers?
